rate: 10
model:
  name: model_onnx
  path: "../Model/bestV5-20e.onnx"
classes:
  name: classes_list
  list: ["Fanta", "Pepsi", "Seven"]
confidence:
  name: conf_threshold
  value: 0.6
cuda:
  name: enable_cuda
  value: True