map_update_interval: 0.1
maxUrange: 3.0
maxRange: 3.0
sigma: 0.05
kernelSize: 1
lstep: 0.05
astep: 0.05
iterations: 2
lsigma: 0.075
ogain: 3.0
lskip: 0
minimumScore: 50
srr: 0.01
srt: 0.02
str: 0.01
stt: 0.02
linearUpdate: 0.02
angularUpdate: 0.0436
temporalUpdate: -1.0
resampleThreshold: 0.5
particles: 100
xmin: -1.0
ymin: -3.0
xmax: 3.0
ymax: 1.0
delta: 0.025
llsamplerange: 0.01
llsamplestep: 0.01
lasamplerange: 0.005
lasamplestep: 0.005