rateClass: 15
model:
  name: model_onnx
  path: "/home/sr_tavo/Ciberfisicos_ws/src/JetAuto2/Model/bestV5-25e.onnx"
classes:
  name: classes_list
  list: ["Fanta", "Pepsi", "Seven"]
confidence:
  name: conf_threshold
  value: 0.7
isCuda:
  name: enable_cuda
  value: False